# Generated by Django 3.0 on 2020-02-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('ages', models.CharField(max_length=200)),
                ('patientType', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=100)),
                ('questionText', models.CharField(max_length=500)),
                ('answerType', models.CharField(max_length=100)),
                ('choices', models.CharField(blank=True, max_length=300)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaireContent', to='API.Questionnaire', to_field='uid')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=100)),
                ('answerType', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=1000)),
                ('answerContent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionAnswer', to='API.AnswerContent')),
            ],
        ),
    ]
