# Generated by Django 3.0 on 2019-12-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20191219_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
